# Generated by Django 4.0.4 on 2023-07-25 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdv', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='subtitulo',
            field=models.TextField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='categoria',
            name='titulo',
            field=models.TextField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
