# Generated by Django 4.0.4 on 2023-07-25 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdv', '0002_categoria_subtitulo_categoria_titulo'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='class_html',
            field=models.TextField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
